version: '3.8'
services:
  db:
    image: postgres:15.1-alpine3.17
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local